@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "AL1S.Ability",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2011053 { 
   	label=AL1S
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Ability2011053[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Ability</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   behaviorName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ ErrorRestore(fight: UnitHuman)</TD></TR>
<TR><TD ALIGN="LEFT" ># RailGunBlaze(fight: UnitHuman, User: PlayerChara)</TD></TR>
<TR><TD ALIGN="LEFT" >+ SystemHack(fight: UnitHuman, user: PlayerChara)</TD></TR>
<TR><TD ALIGN="LEFT" >+ powerup(fight: UnitHuman, user: PlayerChara)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_464145674 { 
   	label=Ability
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Attack1033957431[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Attack</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   Damage: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" ># BasicAttack(fight: UnitHuman, User: PlayerChara): int</TD></TR>
<TR><TD ALIGN="LEFT" ># EnemyAttack(fight: UnitHuman, User: PlayerChara): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Skill1033957431[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Skill</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   HPCost: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   MPCost: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   SkillDamage: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   coolTime: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ ArmorBreak(fight: UnitHuman, User: PlayerChara)</TD></TR>
<TR><TD ALIGN="LEFT" ># MisticArrow()</TD></TR>
<TR><TD ALIGN="LEFT" ># RailGunClamp(fight: UnitHuman, User: PlayerChara)</TD></TR>
<TR><TD ALIGN="LEFT" ># RailGunShoot(fight: UnitHuman, User: PlayerChara)</TD></TR>
<TR><TD ALIGN="LEFT" >+ coreATK(fight: UnitHuman, User: PlayerChara)</TD></TR>
<TR><TD ALIGN="LEFT" >+ statup(User: PlayerChara)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
Ability2011053 -> Attack1033957431[arrowhead=none, arrowtail=empty, dir=both];
Ability2011053 -> Skill1033957431[arrowhead=none, arrowtail=empty, dir=both];
    
}
@enduml